{
 "title": "Дашборд",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}} - CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (windows_cs_physical_memory_bytes - windows_os_physical_memory_free_bytes) / windows_cs_physical_memory_bytes",
     "legendFormat": "{{instance}} - Memory Usage"
    }
   ]
  },
  {
   "title": "Disk Write (C:)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{volume=\"C:\"}[1m])\r\n",
     "legendFormat": "{{volume}} Write"
    }
   ]
  },
  {
   "title": "Disk Read (C:)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{volume=\"C:\"}[1m])\r\n",
     "legendFormat": "{{volume}} Read"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(windows_net_bytes_received_total{interface!~\"Loopback.*|isatap.*|Teredo.*\"}[1m])) * 8",
     "legendFormat": "{{instance}} Received"
    }
   ]
  },
  {
   "title": "Network Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(windows_net_bytes_sent_total{interface!~\"Loopback.*|isatap.*|Teredo.*\"}[1m])) * 8",
     "legendFormat": "{{instance}} Sent"
    }
   ]
  },
  {
   "title": "Promtail Loki Push Latency (P95)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(promtail_request_duration_seconds_bucket{job=\"promtail\"}[5m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Space Used (C:)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (windows_logical_disk_size_bytes{volume=\"C:\"} - windows_logical_disk_free_bytes{volume=\"C:\"}) / windows_logical_disk_size_bytes{volume=\"C:\"}",
     "legendFormat": "{{volume}} Used"
    }
   ]
  },
  {
   "title": "Targets Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up) by (job)", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Total Events (Last Hour)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=~\"windows_.*\"} [1h])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Event Rate by Level (System)\t",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({job=\"windows_system\"} [1m])) by (level)",
     "legendFormat": "{{level}} level"
    }
   ]
  },
  {
   "title": "Event Rate by Level (Security)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({job=\"windows_security\"} [1m])) by (level)",
     "legendFormat": "{{level}} level"
    }
   ]
  },
  {
   "title": "Event Rate by Level (Application)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({job=\"windows_application\"} [1m])) by (level)",
     "legendFormat": "{{level}} level"
    }
   ]
  },
  {
   "title": "Prometheus TSDB Head Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"prometheus\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Promtail Send Rate (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(promtail_sent_bytes_total{job=\"promtail\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Loki Ingestion Rate (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total{job=\"loki\"}[1m])) by (instance)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}