- name: restart postgresql
  become: yes
  service:
    name: postgresql
    state: restarted

- name: restart logical PostgreSQL
  service:
    name: "postgresql@{{ postgresql_version }}-logical"
    state: restarted