---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL is stopped
  service:
    name: postgresql
    state: stopped

- name: Remove existing data directory
  file:
    path: /etc/postgresql/14/main/postgresql.conf
    state: absent

- name: Create replication configuration
  template:
    src: recovery.conf.j2
    dest: /etc/postgresql/14/main/postgresql.conf

- name: Start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes