---
- hosts: postgres_db
  become: yes
  vars:
    replication_password: "securepassword"
    replica_ip: "{{ hostvars['db2']['ansible_host'] }}"
  roles:
    - postgres_db

- hosts: replica_db
  become: yes
  vars:
    replication_password: "securepassword"
    primary_ip: "{{ hostvars['db1']['ansible_host'] }}"
  roles:
    - replica_db
